
@endpoints = https://iy2qrkd4hh.execute-api.us-east-1.amazonaws.com/prod/

GET {{endpoints}}/hello/
###


GET {{endpoints}}/spaces
###

GET {{endpoints}}/spaces?SpaceFinderId=f31dfb60-b8a8-4f80-b4e8-98bb72bc6b74
###

GET {{endpoints}}/spaces?location="New Delhi India"
###

POST {{endpoints}}/spaces/
Content-Type: application/json

{
    "location": "New Delhi",
    "attachment": "Born Here"
}
###

PUT {{endpoints}}/spaces?SpaceFinderId=f31dfb60-b8a8-4f80-b4e8-98bb72bc6b74
Content-Type: application/json

{
    "place": "Palam Colony, Raj Nagar",
    
}